#pragma once

#ifndef AMBER_WITH_EDITOR
#define AMBER_WITH_EDITOR 0
#endif

#ifndef AMBER_WITH_EDITOR_ONLY_DATA
#define AMBER_WITH_EDITOR_ONLY_DATA 0
#endif

#ifndef WITH_EDITOR
#define WITH_EDITOR AMBER_WITH_EDITOR
#endif

#ifndef WITH_EDITOR_ONLY_DATA
#define WITH_EDITOR_ONLY_DATA AMBER_WITH_EDITOR_ONLY_DATA
#endif
